# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy with GitHub Pages dependencies preinstalled
run-name: Deployment Pipeline
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master", "test-github"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci 
    - run: npm run build -- --configuration production --base-href "/website/"
    - run: npm test
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/website/
  # Build job
  # Deployment job

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: dist/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install angular and angular-cli-pages
      run: npm ci
    - name: Deploy to GitHub Pages
      run: npm run deploy 
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
    - name: List Deployed Directory
      run: |
        echo "Contents of the deployment directory:"
        ls -R dist/website/